name: cryptopay
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  json_annotation: ^4.9.0
  dio: ^5.7.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
